import turtle

turtle.penup()
turtle.backward(150)
turtle.pendown()

turtle.circle(50)
turtle.penup()
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(80)
turtle.pendown()
turtle.left(90)
turtle.forward(150)


turtle.penup()
turtle.right(90)
turtle.forward(100)
turtle.right(120)
turtle.pendown()
turtle.forward(150)
turtle.backward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.penup()
turtle.forward(30)
turtle.left(90)
turtle.backward(20)
turtle.pendown()
turtle.forward(150)


turtle.right(90)
turtle.penup()
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.forward(70)
turtle.pendown()
turtle.left(90)
turtle.backward(25)
turtle.forward(150)
turtle.backward(75)
turtle.right(90)
turtle.forward(50)


turtle.exitonclick()
